---
title: "CMS ICD RC"
author: "Fatemeh Kazemi"
date: "2/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
  library(tidyverse)
  library(here)
```

```{r load data}
load(here('data', 'raw','cms-icd-rc.RDa'))
```

```{r}
cuz <- c("cvd","ihd","chf","cbv",
         "resp","copd","pneu","uri","ards",
         "canc","lungc",
         "seps",
         "demn","VaD","AD","NeD","UsD", 
         "diabt","diabt1","diabt2", 
         "kidn")

rc.cat <- c("RECORD_COND_1", "RECORD_COND_2", "RECORD_COND_3", "RECORD_COND_4",
                "RECORD_COND_5", "RECORD_COND_6", "RECORD_COND_7", "RECORD_COND_8")
```

```{r load csv file}
# done and saved
dt.cms.icd.rc <- read.csv(
  here('data', 'raw', 'cms-icd-rc.csv'))

save(dt.cms.icd.rc, file = here('data', 'raw', 'cms-icd-rc.RDa'))
```

```{r}
dt <- dt.cms.icd.rc %>%
  mutate(
    ### ICD main cuases
    ICD_CODE_main = 
      ifelse(str_detect(ICD_CODE, "I"), "cvd",
             ifelse(str_detect(ICD_CODE, "J"), "resp",
                    ifelse(str_detect(ICD_CODE, "C|D"), "canc",
      ifelse(str_detect(ICD_CODE, "A40|A41"), "seps",
             ifelse(str_detect(ICD_CODE, "F01|F03|G30|G31"), "demn",
                    ifelse(str_detect(ICD_CODE, "E10|E11"), "diabt",
                           ifelse(str_detect(ICD_CODE, "N18|N19"), "kidn", 
                                  as.character(ICD_CODE)))))))),
    ### ICD sub causes
    ICD_CODE_sub = 
    ### cvd
      ifelse(str_detect(ICD_CODE, "I20|I21|I22|I23|I24|I25"), "ihd",
             ifelse(str_detect(ICD_CODE, "I50"), "chf",
                    ifelse(str_detect(ICD_CODE, "I6"), "cbv",
    ### resp
      ifelse(str_detect(ICD_CODE, "J40|J41|J42|J43|J44"), "copd",
             ifelse(str_detect(ICD_CODE, "J12|J13|J14|J15|J16|J17|J18"), "pneu",
                    ifelse(str_detect(ICD_CODE, "J00|J01|J02|J03|J04|J05|J06"), "uri",
                           ifelse(str_detect(ICD_CODE, "J80"), "ards",
    ### cancer
      ifelse(str_detect(ICD_CODE, "C34"), "lungc",  
    ### sepsis
      ifelse(str_detect(ICD_CODE, "A40|A41"), "seps",
    ### dementia
      ifelse(str_detect(ICD_CODE, "F01"), "VaD",
             ifelse(str_detect(ICD_CODE, "G30"), "AD",
                    ifelse(str_detect(ICD_CODE, "G31"), "NeD",
                           ifelse(str_detect(ICD_CODE, "F03"), "UsD",
    ### diabetes
      ifelse(str_detect(ICD_CODE, "E10"), "diabt1",
             ifelse(str_detect(ICD_CODE, "E11"), "diabt2",
    ### kidney
       ifelse(str_detect(ICD_CODE, "N18|N19"), "kidn", as.character(ICD_CODE))
    ))))))))))))))))
```

```{r}
for (RCcat in rc.cat){
  ### RC main causes
  dt[,paste0(RCcat,'_main',sep="")] <- 
    ifelse(str_detect(dt[,RCcat], "I"), "cvd",
           ifelse(str_detect(dt[,RCcat],"J"), "resp",
                  ifelse(str_detect(dt[,RCcat], "C|D"), "cance",
    ifelse(str_detect(dt[,RCcat], "A40|A41"), "seps",             
           ifelse(str_detect(dt[,RCcat], "F01|F03|G30|G31"), "demn",
                  ifelse(str_detect(dt[,RCcat], "E10|E11"), "diabt",
                         ifelse(str_detect(dt[,RCcat], "N18|N19"), "kidn",
    as.character(dt[,RCcat]))))))))
  
  ### RC sub causes
  dt[,paste0(RCcat,'_sub',sep="")] <- 
    ### cvd
    ifelse(str_detect(dt[,RCcat], "I20|I21|I22|I23|I24|I25"), "ihd",
           ifelse(str_detect(dt[,RCcat], "I50"), "chf",
                  ifelse(str_detect(dt[,RCcat], "I6"), "cbv",
    ### resp
    ifelse(str_detect(dt[,RCcat], "J40|J41|J42|J43|J44"), "copd",
           ifelse(str_detect(dt[,RCcat], "J12|J13|J14|J15|J16|J17|J18"), "pneu",
                  ifelse(str_detect(dt[,RCcat], "J00|J01|J02|J03|J04|J05|J06"), "uri",
                         ifelse(str_detect(dt[,RCcat], "J80"), "ards",
    ### cancer
    ifelse(str_detect(dt[,RCcat], "C34"), "lungc",    
    ### sepsis
    ifelse(str_detect(dt[,RCcat], "A40|A41"), "seps", 
    ### dementia
    ifelse(str_detect(dt[,RCcat], "F01"), "VaD",
           ifelse(str_detect(dt[,RCcat], "G30"), "AD",
                  ifelse(str_detect(dt[,RCcat], "G31"), "NeD",
                         ifelse(str_detect(dt[,RCcat], "F03"), "UsD",
    ### diabetes
    ifelse(str_detect(dt[,RCcat], "E10"), "diabt1",
           ifelse(str_detect(dt[,RCcat], "E11"), "diabt2",
    ### kidney
    ifelse(str_detect(dt[,RCcat], "N18|N19"), "kidn",
           as.character(dt[,RCcat])))))))))))))))))
}

dt.cms.icd.rc.decoded <- dt

save(dt.cms.icd.rc.decoded, 
     file = here('data', 'processed', 'cms-icd-rc-decoded.RDa'))
write.csv(dt.cms.icd.rc.decoded, 
          file = here('data', 'processed', 'cms-icd-rc-decoded.csv'))
```


```{r}
dt.cms.icd.rc.decoded %>% 
  filter(ICD_CODE_main %in% cuz) %>% 
  group_by(ICD_CODE_main) %>% 
  summarise(n = n())
```


```{r}
dt.cms.icd.rc.decoded %>% 
  filter(ICD_CODE_sub %in% cuz) %>% 
  group_by(ICD_CODE_sub) %>% 
  summarise(n = n())
```


```{r}
dt.cms.icd.rc.decoded %>% 
  filter(RECORD_COND_1_main %in% cuz) %>% 
  group_by(RECORD_COND_1_main) %>% 
  summarise(n = n())
```


```{r}
dt.cms.icd.rc.decoded %>% 
  filter(RECORD_COND_1_sub %in% cuz) %>% 
  group_by(RECORD_COND_1_sub) %>% 
  summarise(n = n())
```